# Site settings
title: "Aline Bispo"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Aline Mariana Bispo de Lima"
resume_title:                   "Mid Wordpress Developer"
#resume_contact_email:           "aline.blima26@gmail.com"
resume_contact_email:           "alinembispolima@gmail.com"
resume_contact_telephone:       "+5585981946408"
resume_contact_address:         ""
resume_header_contact_info: ""
#resume_header_intro: |
  #  <p>Dev Frontend Junior</p>

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
#resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/alinembl"
 # resume_twitter_url:           "http://twitter.com/mari_lih"
  resume_linkedin_url:          "https://www.linkedin.com/in/alinembl"

resume_print_social_links:      true

# Design settings
resume_theme:                   default
